### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by Moeriki** [Acidic9/prettier-plugin-tailwind#1]
I'd love to see JSX support. Looking at the source it looks pretty simple so far.

How big do you estimate the effort to add JSX support?

**Comment by Acidic9** [comment]
It may be extremely simple! Perhaps just creating a new parser which does the same that HTML does, except for JSX... The only issue is that JSX classname can be a JavaScript function `className={() => 'a b c'}` or other values.

I can take some time tomorrow to look into working on a solution for this! Otherwise you can feel free to give it a go with a pull request.

**Comment by mheob** [comment]
In addition, it would be nice to get the support of TWIG.

**Comment by Acidic9** [comment]
Added support for JSX and TSX :)

Will update classes under `className="..."`.

This can be customized with a prettier config:

```yaml
twJsxClassAttributes: "className,customAttribute"
```
